apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- range $key, $val := .Values.configMap_data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

