---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.appName }}-allow
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: {{ .Values.istio.principals }}




