apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
data:
  {{- range $key, $val := .Values.configMap_data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

