{{ if .Values.db_job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-db-job
  labels:
    app: {{ .Values.appName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: db-job
        image: roboshopb84.azurecr.io/roboshop-{{ .Values.appName }}-db-job:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        envFrom:
          - secretRef:
              name: {{ .Values.appName }}
      restartPolicy: Never
  backoffLimit: 0
{{ end }}

