apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: roboshop-{{ .Values.env }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}
  dataFrom:
  - extract:
      key: {{ .Values.appName }}


